language: ruby
rvm:
  - 2.1.0
script:
   - bundle install
   - bundle exec rubocop -v
   - bundle exec rubocop -D .
   - bundle exec rspec --format doc
   - cd examples/redblue
   - bundle install
   - bundle exec ruby generate_report.rb
